function drawHome(canvasId, size, totalHeight) {
    var canvas = document.getElementById(canvasId);
    canvas.width = size;
    canvas.height = totalHeight;
    var ctx = canvas.getContext('2d');
    ctx.save();
    ctx.translate(0, (totalHeight - size) / 2);
    ctx.scale(size / 100, size / 100);
    ctx.strokeStyle = 'rgba(0,0,0,0)';
    ctx.lineCap = 'butt';
    ctx.lineJoin = 'miter';
    ctx.miterLimit = 4;
    ctx.save();
    ctx.fillStyle = "#ffffff";
    ctx.beginPath();
    ctx.moveTo(75, 14.434);
    ctx.lineTo(50, 0);
    ctx.lineTo(25, 14.434);
    ctx.lineTo(0, 28.868);
    ctx.lineTo(0, 30.335);
    ctx.lineTo(0, 53.404);
    ctx.lineTo(0, 100);
    ctx.lineTo(100, 100);
    ctx.lineTo(100, 53.404);
    ctx.lineTo(100, 30.335);
    ctx.lineTo(100, 28.868);
    ctx.lineTo(75, 14.434);
    ctx.closePath();
    ctx.fill();
    ctx.stroke();
    ctx.restore();
    ctx.restore();
}
;

function drawBack(canvasId, size, totalHeight) {
    var canvas = document.getElementById(canvasId);
    canvas.width = size;
    canvas.height = totalHeight;
    var ctx = canvas.getContext('2d');
    ctx.save();
    ctx.translate(0, (totalHeight - size) / 2);
    ctx.scale(size / 100, size / 100);
    ctx.beginPath();
    ctx.moveTo(0, 0);
    ctx.lineTo(53.403, 0);
    ctx.lineTo(53.403, 100);
    ctx.lineTo(0, 100);
    ctx.closePath();
    ctx.clip();
    ctx.translate(0, 0);
    ctx.translate(0, 0);
    ctx.scale(1, 1);
    ctx.translate(0, 0);
    ctx.strokeStyle = 'rgba(0,0,0,0)';
    ctx.lineCap = 'butt';
    ctx.lineJoin = 'miter';
    ctx.miterLimit = 4;
    ctx.save();
    ctx.fillStyle = "#ffffff";
    ctx.beginPath();
    ctx.moveTo(0, 50);
    ctx.lineTo(14.433, 25);
    ctx.lineTo(28.867, 0);
    ctx.lineTo(53.403, 0);
    ctx.lineTo(38.97, 25);
    ctx.lineTo(24.537, 50);
    ctx.lineTo(38.97, 75);
    ctx.lineTo(53.403, 100);
    ctx.lineTo(28.867, 100);
    ctx.lineTo(14.433, 75);
    ctx.lineTo(0, 50);
    ctx.closePath();
    ctx.fill();
    ctx.stroke();
    ctx.restore();
    ctx.restore();
}
;

